version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    volumes:
      - ..:/work:cached
    command: sleep infinity

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "127.0.0.1::10000"  # Blob Service Port
      - "127.0.0.1::10001"  # Queue Service Port
      - "127.0.0.1::10002"  # Table Service Port
    volumes: 
      - articlesummarizerdata:/data

volumes:
  articlesummarizerdata:
    driver: local
